modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "pridetags"
version = "${version}"
displayName = "PrideTags"
authors = "Elty"
description = '''
Display flags and pronouns from pronouns.page
'''
logoFile = "assets/pridetags/icon.png"

[[dependencies.pridetags]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pridetags]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pridetags]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "pridetags.mixins.json"
